# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji
- kramdown

# 3. Gem settings
paginate: 8 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
markdown: kramdown
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: cwhypt # jekyll-seo-tag > Owners twitter username
author: Weihao Cao # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Weihao Cao # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/cwhypt
    - https://www.facebook.com/cwhypt
    - https://www.linkedin.com/in/cwhypt
    - https://plus.google.com/+cwhypt
    - https://github.com/cwhypt

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the Blog page.
    feature_image: "https://unsplash.it/1300/400?image=1015"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Weihao Cao" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "A Math and Physics double major undergraduate student in HKU."
url: "https://weihaocao.com" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/cwhypt"
email: "contact@weihaocao.com"
disqus: "cwhypt" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "https://s.gravatar.com/avatar/a7c692790ced410e01c9a569df148f36" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Resume: /resume/
  Detail Info: https://cwhypt.wixsite.com/main/
  Blog: /blog/
  Categories: /categories/
  Contact: /contact/

navigation_footer:
  Created by Weihao Cao: https://weihaocao.com

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/cwhypt
  LinkedIn: https://www.linkedin.com/in/cwhypt
  Google+: https://plus.google.com/+cwhypt
  GitHub: https://github.com/cwhypt
  link: https://weihaocao.com
  RSS: /feed.xml
  Email: mailto:contact@weihaocao.com

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  #Twitter: "#1DA1F2"
  #facebook: "#3B5998"
  #Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
